'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")>  _
Partial Friend NotInheritable Class GUI
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As GUI = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New GUI()),GUI)
    
    Public Shared ReadOnly Property [Default]() As GUI
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("90, 100, 105")>  _
    Public ReadOnly Property MAIN_BACK_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("MAIN_BACK_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("100, 110, 115")>  _
    Public ReadOnly Property TOP_PANEL_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("TOP_PANEL_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("140, 145, 150")>  _
    Public ReadOnly Property MAIN_BORDER_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("MAIN_BORDER_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("155, 160, 165")>  _
    Public ReadOnly Property MAIN_TEXT_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("MAIN_TEXT_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("120, 130, 135")>  _
    Public ReadOnly Property CTRL_BTNS_HOVER_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("CTRL_BTNS_HOVER_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("75, 85, 95")>  _
    Public ReadOnly Property CTRL_BTNS_PRESS_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("CTRL_BTNS_PRESS_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("165, 170, 175")>  _
    Public ReadOnly Property TEXT_SELECT_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("TEXT_SELECT_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("65, 70, 75")>  _
    Public ReadOnly Property MAIN_DARK_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("MAIN_DARK_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("100, 110, 115")>  _
    Public ReadOnly Property SCROLL_BAR_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_BAR_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("105, 115, 120")>  _
    Public ReadOnly Property SCROLL_BAR_HOVER_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_BAR_HOVER_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("120, 130, 135")>  _
    Public ReadOnly Property SCROLL_BAR_MOUSE_DOWN_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_BAR_MOUSE_DOWN_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("100, 110, 115")>  _
    Public ReadOnly Property SCROLL_ARROW_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_ARROW_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("105, 115, 120")>  _
    Public ReadOnly Property SCROLL_ARROW_HOVER_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_ARROW_HOVER_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("120, 130, 135")>  _
    Public ReadOnly Property SCROLL_ARROW_MOUSE_DOWN_COLOR() As Global.System.Drawing.Color
        Get
            Return CType(Me("SCROLL_ARROW_MOUSE_DOWN_COLOR"),Global.System.Drawing.Color)
        End Get
    End Property
End Class
